version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
    assignees:
      - 'Jamie-BitFlight'
    reviewers:
      - 'Jamie-BitFlight'
    labels:
      - 'github-actions'
      - 'dependencies'
    commit-message:
      prefix: 'build'
      include: 'scope'
    groups:
      github-actions:
        patterns:
          - '*'
    open-pull-requests-limit: 10

  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
    assignees:
      - 'Jamie-BitFlight'
    reviewers:
      - 'Jamie-BitFlight'
    labels:
      - 'npm'
      - 'dependencies'
    commit-message:
      prefix: 'build'
      prefix-development: 'build'
      include: 'scope'
    groups:
      production-dependencies:
        dependency-type: 'production'
        update-types:
          - 'minor'
          - 'patch'
      dev-dependencies:
        dependency-type: 'development'
        update-types:
          - 'minor'
          - 'patch'
    open-pull-requests-limit: 10
    versioning-strategy: 'increase'
