projects:
  PROJECT1:
    ignored_states:
      - Done
    to_state:
      In Progress:
        - eventName: pull_request
          action: opened
        - eventName: pull_request
          action: synchronize
      Done:
        - eventName: pull_request
          action: closed
          payload:
            pull_request:
              merged: true
