projects:
  UNICORN:
    ignored_states:
      - 'done'
      - 'testing'
    to_state:
      'solution review':
        - eventName: create
      'code review':
        - eventName: pull_request
          action: 'opened'
        - eventName: pull_request
          action: 'synchronize'
      'testing':
        - eventName: pull_request
          payload:
            pull_request:
              merged: true
          action: 'closed'
        - eventName: pull_request_review
          payload:
            review:
              state: 'approved'
  DVPS:
    ignored_states:
      - 'done'
      - 'testing'
    to_state:
      'In Progress':
        - eventName: create
      'Code Review':
        - eventName: pull_request
          action: 'opened'
        - eventName: pull_request
          action: 'synchronize'
      'testing':
        - eventName: pull_request
          payload:
            pull_request:
              merged: true
          action: 'closed'
        - eventName: pull_request_review
          payload:
            review:
              state: 'approved'
