name: Jira Transition Manager
description: This action will transition the list of Jira issues provided between states, or it will display the available transitions and the current issue state.
branding:
  icon: 'chevron-right'
  color: 'blue'
inputs:
  issues:
    description: A comma delimited list of one or more Jira issues to be transitioned
    required: true
  jira_transitions_yaml:
    description: >
      YAML configuration that overrides the configuration in the `.github/github_event_jira_transitions.yml` file.

    required: false
  jira_base_url:
    description: >
      The Jira cloud base url including protocol i.e. 'https://company.atlassian.net'
      or use environment variable JIRA_BASE_URL
    required: false
  jira_user_email:
    description: >
      The Jira cloud user email address
      or use environment variable JIRA_USER_EMAIL
    required: false
  jira_api_token:
    description: >
      The Jira cloud user api token
      or use environment variable JIRA_API_TOKEN
    required: false
  fail-on-error:
    description: If there is an error during transition, the action will error out.
    default: false
    required: false
outputs:
  issueOutputs:
    description: >
      A JSON list of Jira Issues and their transition details

runs:
  using: 'node12'
  main: './dist/index.js'
